version: "3.8"
services:
  mongo:
    image: mongo
    container_name: abe_mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  app:
    depends_on:
      - "mongo"
    environment:
      MONGODB_URI: mongodb://mongo:27017/project1
    build: ./hotelApp
    ports:
      - "3000:3000"
  rabbitmq:
    image: rabbitmq:3.8.14-management-alpine
    container_name: "rabbitmq"
    hostname: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/lib/:/var/lib/rabbitmq/
      - ./rabbimq/log/:/var/log/rabbitmq
  bookingsender:
    container_name: bookingSender
    restart: always
    depends_on:
      - "rabbitmq"
    build: ./BookingSender
  reservationhandler:
    container_name: reservationHandler
    restart: always
    environment:
      MONGODB_URI: mongodb://mongo:27017/project1
    depends_on:
      - "rabbitmq"
      - "mongo"
    build: ./reservationHandler
  confirmationhandler:
    container_name: confirmationHandler
    restart: always
    depends_on:
      - "rabbitmq"
      - "mongo"
    build: ./confirmationhandler
